### PR TITLE
User has end date

### LINKED ISSUE #314: need to be able to set end-date for personnel in admin portal

### PR DESCRIPTION
**Pull request by palbock**
Ansattes sluttdato kan vises og redigeres i adminpanel.
Closes #314

### CODE REVIEW

**Review by Trulsaa — CHANGES_REQUESTED** [review]
Sending this as the body 

```
[{"name":"Pål","email":"p@p.p","startDate":"2021-07-02T15:28:00.000Z","endDate":"2021-12-02T16:28:00.000Z"}]
``` 
to POST | http://localhost:8081/api/admin/Users gives this as the response

```
[{"id":1003,"name":"Pål","email":"p@p.p","startDate":"2021-07-02","endDate":null}]
```

The sendt endDate is missing in the respons. Adding a user with an endDate does not work.

**Comment by Trulsaa** [comment]
React code looks good 👌

**Comment by palbock** [comment]
> 
> 
> Sending this as the body
> 
> ```
> [{"name":"Pål","email":"p@p.p","startDate":"2021-07-02T15:28:00.000Z","endDate":"2021-12-02T16:28:00.000Z"}]
> ```
> 
> to POST | http://localhost:8081/api/admin/Users gives this as the response
> 
> ```
> [{"id":1003,"name":"Pål","email":"p@p.p","startDate":"2021-07-02","endDate":null}]
> ```
> 
> The sendt endDate is missing in the respons. Adding a user with an endDate does not work.

Should work now

**Comment by Trulsaa** [comment]
> > Sending this as the body
> > ```
> > [{"name":"Pål","email":"p@p.p","startDate":"2021-07-02T15:28:00.000Z","endDate":"2021-12-02T16:28:00.000Z"}]
> > ```
> > 
> > 
> > to POST | http://localhost:8081/api/admin/Users gives this as the response
> > ```
> > [{"id":1003,"name":"Pål","email":"p@p.p","startDate":"2021-07-02","endDate":null}]
> > ```
> > 
> > 
> > The sendt endDate is missing in the respons. Adding a user with an endDate does not work.
> 
> Should work now

Confirmed working :)

**Review by martiskj — APPROVED** [review]

**Review by Trulsaa — APPROVED** [review]

**Pull request merged**
